### ISSUE TITLE
Session username needs to be retrieved from the database

### ISSUE THREAD

**Issue by lautaroangelico** [lautaroangelico/WebEngine#18]
https://github.com/lautaroangelico/WebEngine/blob/7411cb8934f24a74b2f99eea3c8882a8cca3842c/includes/classes/class.login.php#L72

Current method has conflicts with usernames with upper and lowercase letters.

**Comment by jokerosx** [comment]
why u don't set all to lowercase ?

**Comment by lautaroangelico** [comment]
Some databases might be case sensitive, so it's better to have it retrieve the data exactly as it is in the database.
