### ISSUE TITLE
Wrong variable for Master Level info

### ISSUE THREAD

**Issue by lautaroangelico** [lautaroangelico/WebEngine#34]
https://github.com/lautaroangelico/WebEngine/blob/a06bd8f037b1a3d9a7c633fe9e4df01dc77ec499/includes/classes/class.character.php#L216

**Comment by Wortex** [comment]
`$characterMLData = $this->getMasterLevelInfo($character_name);`

Add this above that line

**Comment by lautaroangelico** [comment]
Fixed in 1.2.1
