### ISSUE TITLE
VIP System bug for IGCN files

### ISSUE THREAD

**Issue by juangreve** [lautaroangelico/WebEngine#5]
The vip system does not work properly, throws the following error:
[http://imgur.com/NK3P3eF](url)

**Comment by lautaroangelico** [comment]
The current IGCN VIP module is compatible with their S9 table structure. Apparently they changed it on their newest files.

**Comment by lautaroangelico** [comment]
class.vip.igcn.php contructor is only loading the MuOnline database even when using Me_MuOnline, will apply fix in the next patch.

**Comment by lautaroangelico** [comment]
line 101 on class.vip.igcn.php needs Me_MuOnline to be included for the credit system

**Comment by lautaroangelico** [comment]
Fixed in patch 1.0.9.7
