### ISSUE TITLE
iis installation

### ISSUE THREAD

**Issue by xshion13** [lautaroangelico/WebEngine#56]
Hello, i tried to run this in IIS but having issue with __ROOT_DIR__ pointing to http://my_ip**c/inetpub/wwwroot/**templates/default/css/castle-siege.css

i tried to change this but it says can't define functions after swapping. any suggestion? thanks

**Comment by ibhost-com-br** [comment]
I created a fix for this
https://www.creandomu.com/index.php?topic=4397.msg17937#new
