### ISSUE TITLE
Getting this error when trying to enter localhost

### ISSUE THREAD

**Issue by LDC-ar** [lautaroangelico/WebEngine#57]
Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in C:\xampp\htdocs\includes\functions.php:15 Stack trace: #0 C:\xampp\htdocs\includes\functions.php(276): check_value('') #1 C:\xampp\htdocs\includes\webengine.php(117): webengineConfigs() #2 C:\xampp\htdocs\index.php(20): include_once('C:\\xampp\\htdocs...') #3 {main} thrown in C:\xampp\htdocs\includes\functions.php on line 15

**Comment by Apryed** [comment]
Same...

**Comment by KarlStruv** [comment]
Yes! I can confirm that this error appears only in newer PHP versions. Apryed's fix did the trick for me!

**Comment by lautaroangelico** [comment]
This has been fixed with in the soon to be released 1.2.5 update.
https://github.com/lautaroangelico/WebEngine/commit/8a1d9ce8a704e03a95f66738903f88856e267001
