### ISSUE TITLE
Regarding how the official plugins load language files

### ISSUE THREAD

**Issue by amarillonmc** [lautaroangelico/WebEngine#65]
In all of the officially provided plugins ``loader.php``, there are this snippet that decides which language to load:
(Example Taken from Change Class Plugin)

```
// language phrases
if(file_exists(__PATH_CHANGECLASS_ROOT__ . 'languages/'.config('language_default', true).'/language.php')) {
	// attempt to load same language as website
	if(!@include_once(__PATH_CHANGECLASS_ROOT__ . 'languages/'.config('language_default', true).'/language.php')) throw new Exception('Error loading language file (changeclass).');
} else {
	// load default language file (en)
	if(!@include_once(__PATH_CHANGECLASS_ROOT__ . 'languages/en/language.php')) throw new Exception('Error loading language file (changeclass).');

 }
```

However, it only checks for the ``language_default`` value in the configs, and not ``$_SESSION['language_display']``, which means even if a translation is provided by populating the `language.php` file, and the user switched to said language, the plugin language will still be in the ``language_default`` value, defeating the purpose of multi-language.

Please advise, thanks.

**Comment by 211211** [comment]
I don't think they will maintain this repo anymore. For a quick fix, we can do it ourselves.

`
// Determine the language to use
$language = isset($_SESSION['language_display']) ? $_SESSION['language_display'] : config('language_default', true);

// language phrases
if (file_exists(__PATH_VIP_ROOT__ . 'languages/' . $language . '/language.php')) {
    // attempt to load the language file
    if (!@include_once(__PATH_VIP_ROOT__ . 'languages/' . $language . '/language.php')) {
        throw new Exception('Error loading language file (vip).');
    }
} else {
    // load default language file (en)
    if (!@include_once(__PATH_VIP_ROOT__ . 'languages/en/language.php')) {
        throw new Exception('Error loading language file (vip).');
    }
}
`

**Comment by aznrob** [comment]
How can you install a plugin? For example I'm trying to install the VIP plugin. I added the __uploads files to root. Then tried loading the plug.xml file from admincp but getting Plugin file(s) missing error.

**Comment by amarillonmc** [comment]
1) You shall add the _contents_ of ``__upload`` folder to root, not uploading the folder itself to root.
2) You may have a version of WebEngine that has a check on "legit" plugins, the check needs to be disabled (by commenting out a certain part of a certain file, I can't remember - but you can find the "patched" file everywhere on MU related forums now)

I'll close this one since the initial problem is solved.
