### ISSUE TITLE
No connect the error message shows the username and password for the MSSQL 

### ISSUE THREAD

**Issue by bedamusa** [lautaroangelico/WebEngine#9]
When there is no connect the error message shows the username and password for the MSSQL server.

`Warning: Uncaught PDOException: SQLSTATE[08001] SQLDriverConnect: 17 [Microsoft][ODBC SQL Server Driver][DBNETLIB]SQL Server in ******\webengine\includes\classes\class.database.php:25 Stack trace: #0 *****\webengine\includes\classes\class.database.php(25): PDO->__construct('odbc:Driver={SQ...') #1 *******\webengine\includes\webengine.php(141): dB->__construct('*********', '1433', 'MuOnline', 'sa', '*********', '3') #2 ********\webengine\index.php(20): include_once('...................') #3 {main} thrown in *****************\webengine\includes\classes\class.database.php on line 25
`

**Comment by lautaroangelico** [comment]
You have debug mode enable, that's why the website shows all error messages.
